config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  get 'account', to: 'users#account', as: 'account'
  
  
  resources :pros do
    get 'results', on: :collection
    get 'quiz',    on: :collection
    resources :bookings, only: [:new, :create]
  end
  
  root 'pros#index'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	  include Bootsy::Container
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @blogs = Blog.all
    respond_with(@blogs)
  end

  def show
    respond_with(@blog)
  end

  def new
    @blog = Blog.new
    respond_with(@blog)
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    respond_with(@blog)
  end

  def update
    @blog.update(blog_params)
    respond_with(@blog)
  end

  def destroy
    @blog.destroy
    respond_with(@blog)
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :content, :look, :feel, :be, :author, :bootsy_image_gallery_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, as: :bootsy %>
    <%= f.input :look, as: :boolean %>
    <%= f.input :feel, as: :boolean  %>
    <%= f.input :be, as: :boolean  %>
    <%= f.input :author %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Look</th>
      <th>Feel</th>
      <th>Be</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.look %></td>
        <td><%= blog.feel %></td>
        <td><%= blog.be %></td>
        <td><%= blog.author %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content.html_safe %>
</p>



<p>
  <strong>Look:</strong>
  <%= @blog.look %>
</p>

<p>
  <strong>Feel:</strong>
  <%= @blog.feel %>
</p>

<p>
  <strong>Be:</strong>
  <%= @blog.be %>
</p>

<p>
  <strong>Author:</strong>
  <%= @blog.author %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>