config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  get 'account', to: 'users#account', as: 'account'
  
  
  resources :pros do
    get 'results', on: :collection
    get 'quiz',    on: :collection
    resources :bookings, only: [:new, :create]
  end
  
  root 'pros#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <%= link_to 'Quiz', quiz_pros_path, class: 'btn btn-default navbar-btn' %>
      <%= link_to 'New Pro', new_pro_path, class: 'btn btn-default navbar-btn' %>
      <%= link_to 'Blog', blogs_path, class: 'btn btn-default navbar-btn' %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">  Manage Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account Overview", account_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>