config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  get 'account', to: 'users#account', as: 'account'
  
  
  resources :pros do
    get 'results', on: :collection
    get 'quiz',    on: :collection
    resources :bookings, only: [:new, :create]
  end
  
  root 'pros#index'
end

app/models/pro.rb
# == Schema Information
#
# Table name: pros
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Pro < ActiveRecord::Base
  has_many :bookings
	has_one  :workout,  inverse_of: :pro, dependent: :destroy
	has_one  :location, inverse_of: :pro, dependent: :destroy	
	has_one  :style,    inverse_of: :pro, dependent: :destroy

  accepts_nested_attributes_for :workout,
    reject_if: :all_blank, 
    allow_destroy: true
	accepts_nested_attributes_for :location,
    reject_if: :all_blank, 
    allow_destroy: true	
	accepts_nested_attributes_for :style,
    reject_if: :all_blank, 
    allow_destroy: true
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "default.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, :description, presence: true
end

app/controllers/pros_controller.rb
class ProsController < ApplicationController
  before_action :set_pro, only: [:show, :edit, :update, :destroy]

  # GET /pros
  # GET /pros.json
  def index
    # on the index page we want to filter on the same page
    # quiz page will deliver results on a new page
     if params[:q]
      @params = params[:q]
      @params.delete(:workout_weights_true) if @params[:workout_weights_true] == '0'
      @params.delete(:workout_yoga_true)    if @params[:workout_yoga_true] == '0'
      @params.delete(:workout_running_true) if @params[:workout_running_true] == '0'

      @params.delete(:location_hollywood_true)    if @params[:location_hollywood_true] == '0'
      @params.delete(:location_westside_true)     if @params[:location_westside_true] == '0'
      @params.delete(:location_valley_true)       if @params[:location_valley_true] == '0'
      @params.delete(:location_century_city_true) if @params[:location_century_city_true] == '0'
    else
      @params = []
    end

    @q = Pro.ransack(@params)
    @pros = @q.result(distinct: true).includes(:workout)
  end

  def quiz
    @pros = Pro.all
  end
  # GET /pros/1
  # GET /pros/1.json
  def show
  end


  # GET /pros/new
  def new
    @pro = Pro.new
    @pro.build_workout
    @pro.build_location
    @pro.build_style
    @pro.style.approach = 10
    @pro.style.intensity = 10
    @pro.style.plan = 10
  end

  # GET /pros/1/edit
  def edit
  end

  # POST /pros
  # POST /pros.json
  def create
    @pro = Pro.new(pro_params)

    respond_to do |format|
      if @pro.save
        format.html { redirect_to @pro, notice: 'Pro was successfully created.' }
        format.json { render :show, status: :created, location: @pro }
      else
        format.html { render :new }
        format.json { render json: @pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pros/1
  # PATCH/PUT /pros/1.json
  def update
    respond_to do |format|
      if @pro.update(pro_params)
        format.html { redirect_to @pro, notice: 'Pro was successfully updated.' }
        format.json { render :show, status: :ok, location: @pro }
      else
        format.html { render :edit }
        format.json { render json: @pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pros/1
  # DELETE /pros/1.json
  def destroy
    @pro.destroy
    respond_to do |format|
      format.html { redirect_to pros_url, notice: 'Pro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def results
    if params[:q]
      @params = params[:q]
      @params.delete(:workout_weights_true) if @params[:workout_weights_true] == '0'
      @params.delete(:workout_yoga_true)    if @params[:workout_yoga_true] == '0'
      @params.delete(:workout_running_true) if @params[:workout_running_true] == '0'

      @params.delete(:location_hollywood_true)    if @params[:location_hollywood_true] == '0'
      @params.delete(:location_westside_true)     if @params[:location_westside_true] == '0'
      @params.delete(:location_valley_true)       if @params[:location_valley_true] == '0'
      @params.delete(:location_century_city_true) if @params[:location_century_city_true] == '0'

      score = @params[:style_approach_eq].to_i +
              @params[:style_intensity_eq].to_i +
              @params[:style_plan_eq].to_i

      @params.delete(:style_approach_eq) 
      @params.delete(:style_intensity_eq)  
      @params.delete(:style_plan_eq) 

    else
      @params = []
    end

    @q = Pro.ransack(@params)
    @pros = @q.result(distinct: true).includes(:workout, :location, :style)
    @pros = @pros.select { |pro| pro.style.score <= score }
            .sort { |a,b| b.style.score <=> a.style.score }
            .first(3)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pro
      @pro = Pro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pro_params
      params.require(:pro).permit(
        :name, :description, :image, 
        workout_attributes:  [:weights, :yoga, :running],
        location_attributes: [:hollywood, :westside, :valley, :century_city],
        style_attributes:    [:approach, :intensity, :plan]
      )
    end
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/views/pros/_form.html.erb
<%= simple_form_for(@pro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image, :as => :file %>

    <div class="row">
      <div class="col-sm-6">
        <h3>Workouts</h3>
        <div id='workouts'>
          <%= f.simple_fields_for :workout do |workout| %>
            <%= render 'workout_fields', :f => workout %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6">
        <h3>Locations</h3>
        <div id='locations'>
          <%= f.simple_fields_for :location do |location| %>
            <%= render 'location_fields', :f => location %>
          <% end %>
        </div>
      </div>
    </div>

    <h3>Workout style</h3>
    <div id='styles'>
      <%= f.simple_fields_for :style do |style| %>
        <%= render 'style_fields', :f => style %>
      <% end %>
    </div>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/pros/_location_fields.html.erb
<div class='nested-fields'>
  <%= f.input :hollywood, :as => :boolean %>
  <%= f.input :westside, :as => :boolean %>
  <%= f.input :valley, :as => :boolean %>
  <%= f.input :century_city, :as => :boolean %>
</div>

app/views/pros/_style_fields.html.erb
<div class='nested-fields'>
  <%= f.input :approach, collection: Style::APPROACH,
    as: :radio_buttons, label: 'What type of workout experiences do you coach:' %>
  <%= f.input :intensity, collection: Style::INTENSITY,
    as: :radio_buttons, label: 'After a workout, my clients feel:' %>
  <%= f.input :plan, collection: Style::PLAN,
    as: :radio_buttons, label: 'I am a trainer who:' %>
</div>

app/views/pros/_workout_fields.html.erb
<div class='nested-fields'>
  <%= f.input :weights, :as => :boolean %>
  <%= f.input :yoga, :as => :boolean %>
  <%= f.input :running, :as => :boolean %>
</div>

app/views/pros/edit.html.erb
<h1>Editing pro</h1>

<%= render 'form' %>

<%= link_to 'Show', @pro %> |
<%= link_to 'Back', pros_path %>

app/views/pros/index.html.erb
<% if user_signed_in? %>
  <h1>Welcome <%= current_user.name %> </h1> 
  <h2>Your have <%= current_user.sessions %> sessions remaining to book</h2> <br>
<% end %>

<h1>All pros</h1>


<div class="well well-sm">
  <p><strong>Refine the pros: </strong></p>

  <%= search_form_for @q do |f| %>
    <%= f.input :workout_weights_true, as: :boolean, label: "Weights" %>
    <%= f.input :workout_yoga_true, as: :boolean, label: "Yoga" %>
    <%= f.input :workout_running_true, as: :boolean, label: "Running" %>
  <p><strong>Locations served: </strong></p>
    <%= f.input :location_hollywood_true, as: :boolean, label: "Hollywood" %>
    <%= f.input :location_westside_true, as: :boolean, label: "Westside" %>
    <%= f.input :location_valley_true, as: :boolean, label: "Valley" %>
    <%= f.input :location_century_city_true, as: :boolean, label: "Century City" %>

    <%= f.button :submit, class: 'btn btn-danger' %>
  <% end %>
   <br>
   <p>Or find the perfect match!   <%= link_to 'Take the Quiz', quiz_pros_path, class: 'btn btn-info' %>     </p> 


</div>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>      
      <th>Name</th>
      <th>Description</th>
      <th>Workout</th>
      <th>Location</th>      
      <th>Intesity Score</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pros.each do |pro| %>
      <tr>
        <td><%= image_tag pro.image.url(:thumb) %></td>
        <td><%= pro.name %></td>
        <td><%= pro.description %></td>
        <td>
          <ul>
            <%= pro.workout.weights ? raw('<li>Weights</li>') : nil %>
            <%= pro.workout.yoga ? raw('<li>Yoga</li>') : nil %>
            <%= pro.workout.running ? raw('<li>Running</li>') : nil %>
          </ul>
        </td>
        <td>
          <ul>
            <%= pro.location.hollywood ? raw('<li>Hollywood</li>') : nil %>
            <%= pro.location.westside ? raw('<li>Westside</li>') : nil %>
            <%= pro.location.valley ? raw('<li>Valley</li>') : nil %>
            <%= pro.location.century_city ? raw('<li>Century City</li>') : nil %>
          </ul>
        </td>
        <td><%=  pro.try(:score) %></td>   
        <td><%= link_to 'Show', pro %></td>
        <td><%= link_to 'Edit', edit_pro_path(pro) %></td>
        <td><%= link_to 'Destroy', pro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pros/new.html.erb
<h1>New pro</h1>

<%= render 'form' %>

<%= link_to 'Back', pros_path %>

app/views/pros/quiz.html.erb
<h1>Pro Matcher - find your right trainer</h1>

<div class="well well-sm">
  <%= search_form_for @q, url: results_pros_path do |f| %>

    <h2>What type of workout do you want?</h2>
    <%= f.input :workout_weights_true, as: :boolean, label: "Weights" %>
    <%= f.input :workout_yoga_true, as: :boolean, label: "Yoga" %>
    <%= f.input :workout_running_true, as: :boolean, label: "Running" %>
    
    <h2>What's your location?</h2>
    <%= f.input :location_hollywood_true, as: :boolean, label: "Hollywood" %>
    <%= f.input :location_westside_true, as: :boolean, label: "Westside" %>
    <%= f.input :location_valley_true, as: :boolean, label: "Valley" %>
    <%= f.input :location_century_city_true, as: :boolean, label: "Century City" %>
    
    <h2>Workout style</h2>
    <%= f.input :style_approach_eq, collection: Style::APPROACH,
      as: :radio_buttons, label: 'What type of workout experiences do you want?', required: false %>
    <%= f.input :style_intensity_eq, collection: Style::INTENSITY,
      as: :radio_buttons, label: 'After a workout, I like to feel:', required: false %>
    <%= f.input :style_plan_eq, collection: Style::PLAN,
      as: :radio_buttons, label: 'I like a trainer who', required: false %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/pros/results.html.erb
<h1>Search result</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>      
      <th>Name</th>
      <th>Description</th>
      <th>Workout</th>
      <th>Location</th>      
      <th>Intesity Score</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pros.each do |pro| %>
      <tr>
        <td><%= image_tag pro.image.url(:thumb) %></td>
        <td><%= pro.name %></td>
        <td><%= pro.description %></td>
        <td>
          <ul>
            <%= pro.workout.weights ? raw('<li>Weights</li>') : nil %>
            <%= pro.workout.yoga ? raw('<li>Yoga</li>') : nil %>
            <%= pro.workout.running ? raw('<li>Running</li>') : nil %>
          </ul>
        </td>
        <td>
          <ul>
            <%= pro.location.hollywood ? raw('<li>Hollywood</li>') : nil %>
            <%= pro.location.westside ? raw('<li>Westside</li>') : nil %>
            <%= pro.location.valley ? raw('<li>Valley</li>') : nil %>
            <%= pro.location.century_city ? raw('<li>Century City</li>') : nil %>
          </ul>
        </td>
        <td><%= pro.style.score %></td>   
        <td><%= link_to 'Show', pro %></td>
        <td><%= link_to 'Edit', edit_pro_path(pro) %></td>
        <td><%= link_to 'Destroy', pro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pro.name %>
</p>


<p>
<%= image_tag @pro.image.url(:thumb) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pro.description %>
</p>

<h2>Workout types</h2>

<ul>
  <%= @pro.workout.weights ? raw('<li>Weights</li>') : nil %>
  <%= @pro.workout.yoga ? raw('<li>Yoga</li>') : nil %>
  <%= @pro.workout.running ? raw('<li>Running</li>') : nil %>
</ul>

<% if !@pro.workout.weights && !@pro.workout.yoga && !@pro.workout.running %>
  <p>none available</p>
<% end %>

<h2>Locations</h2>

<ul>
  <%= @pro.location.hollywood ? raw('<li>Hollywood</li>') : nil %>
  <%= @pro.location.westside ? raw('<li>Westside</li>') : nil %>
  <%= @pro.location.valley ? raw('<li>Valley</li>') : nil %>
  <%= @pro.location.century_city ? raw('<li>Century City</li>') : nil %>  
</ul>

<% if !@pro.location.hollywood && !@pro.location.westside && !@pro.location.valley && !@pro.location.century_city %>
  <p>none available</p>
<% end %>

<h2>Workout style</h2>

<ul>
  <li><%= @pro.style.approach %></li>
  <li><%= @pro.style.intensity %></li>
  <li><%= @pro.style.plan %></li>
</ul>

<h2>Book this pro</h2>

<%= link_to "Book this pro", new_pro_booking_path(@pro), class: "btn btn-primary" %><br/>

<%= link_to 'Edit', edit_pro_path(@pro) %> |
<%= link_to 'Back', pros_path %>